### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by avaican** [theAeon/PCMRPG#14]
1. Name can be left blank
2. When "P" is selected on quest 1, game crashes
3. No prompt when selecting incorrect option in main menu
4. Save function fails
5. Story poorly written
6. Author of EXE not signed; AV and Defender block game; manual disable required
7. Microcenter is trademark, not credited or capitalized
8. Next quest sometimes fails to load after loading save

MRW I try to play this game:
https://upload.wikimedia.org/wikipedia/commons/c/c7/Frustrated_man_at_a_desk_%28cropped%29.jpg

**Comment by theAeon** [comment]
1. Will fix.
2. Did you type it exactly as written? Capital? No? Not a bug. Also not a crash. If it really is a crash then give me a traceback.
3.Will fix
4. Description or traceback.
5. Not a bug.
6. I have no money, it's not going to be signed. Stop using Norton Grandmavirus.
7. Are you their lawyers?
8. Output of player info please.

**Comment by avaican** [comment]
2. Similar programs are never case sensitive. It is a terrible idea to force case-sensitivity. 
5. Fix anyways
6. http://stackoverflow.com/questions/252226/signing-a-windows-exe-file
7. It would be better capitalized.
8. Begin new game > Save > Close > Open > Load > Next

**Comment by theAeon** [comment]
1. Will fix.
2. Which are you referring to? Markdown is a pain in the ass.
3. From what I understand that requires you to have my cert authority. Also, not worth the effort. No one cares that isn't you.
4. Still not a bug.
5. Cannot reproduce.

**Comment by theAeon** [comment]
All of the actual bugs have been squashed in the testing branch. Labeling rest "wont_fix"
